// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVsUCRNKXmmomC-PxE8FN7TvCsadi7N_g',
    appId: '1:797758895733:web:6bccecff5fe78ef85eea3c',
    messagingSenderId: '797758895733',
    projectId: 'attendance-app-37134',
    authDomain: 'attendance-app-37134.firebaseapp.com',
    storageBucket: 'attendance-app-37134.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjkYHhO6O26yR7SubAK6J6S3gb4U19n_o',
    appId: '1:797758895733:android:95ab1e8842ca55f15eea3c',
    messagingSenderId: '797758895733',
    projectId: 'attendance-app-37134',
    storageBucket: 'attendance-app-37134.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBourWpnfGnPp3d2h36PUFY_KjgX4plwhk',
    appId: '1:797758895733:ios:c3e619d6c0e93be05eea3c',
    messagingSenderId: '797758895733',
    projectId: 'attendance-app-37134',
    storageBucket: 'attendance-app-37134.appspot.com',
    iosClientId: '797758895733-srj708kj05m141r3itga45ajcpq9p74a.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBourWpnfGnPp3d2h36PUFY_KjgX4plwhk',
    appId: '1:797758895733:ios:c3e619d6c0e93be05eea3c',
    messagingSenderId: '797758895733',
    projectId: 'attendance-app-37134',
    storageBucket: 'attendance-app-37134.appspot.com',
    iosClientId: '797758895733-srj708kj05m141r3itga45ajcpq9p74a.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
